version : "3.8"
services:
  authservice:
    build: ./authservice
    ports:
     - "3000:3000"
  
  group-service:
    build: ./group-service
    ports:
      - "3001:3001"
  
  mongodb:
    image: mongo:8
    ports:
    - "27017:27017"
    volumes: 
    - mongo-data:/data/db

volumes:
  mongo-data:
